// Code generated by MockGen. DO NOT EDIT.
// Source: ./models/boolean_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "boolean-as-a-service/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockbooleanRepoInterface is a mock of booleanRepoInterface interface
type MockbooleanRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockbooleanRepoInterfaceMockRecorder
}

// MockbooleanRepoInterfaceMockRecorder is the mock recorder for MockbooleanRepoInterface
type MockbooleanRepoInterfaceMockRecorder struct {
	mock *MockbooleanRepoInterface
}

// NewMockbooleanRepoInterface creates a new mock instance
func NewMockbooleanRepoInterface(ctrl *gomock.Controller) *MockbooleanRepoInterface {
	mock := &MockbooleanRepoInterface{ctrl: ctrl}
	mock.recorder = &MockbooleanRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockbooleanRepoInterface) EXPECT() *MockbooleanRepoInterfaceMockRecorder {
	return m.recorder
}

// CreateBoolean mocks base method
func (m *MockbooleanRepoInterface) CreateBoolean(boolean models.Boolean) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBoolean", boolean)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBoolean indicates an expected call of CreateBoolean
func (mr *MockbooleanRepoInterfaceMockRecorder) CreateBoolean(boolean interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBoolean", reflect.TypeOf((*MockbooleanRepoInterface)(nil).CreateBoolean), boolean)
}

// GetBooleanByID mocks base method
func (m *MockbooleanRepoInterface) GetBooleanByID(id string) (models.Boolean, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooleanByID", id)
	ret0, _ := ret[0].(models.Boolean)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBooleanByID indicates an expected call of GetBooleanByID
func (mr *MockbooleanRepoInterfaceMockRecorder) GetBooleanByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooleanByID", reflect.TypeOf((*MockbooleanRepoInterface)(nil).GetBooleanByID), id)
}

// UpdateBoolean mocks base method
func (m *MockbooleanRepoInterface) UpdateBoolean(boolean models.Boolean) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBoolean", boolean)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBoolean indicates an expected call of UpdateBoolean
func (mr *MockbooleanRepoInterfaceMockRecorder) UpdateBoolean(boolean interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBoolean", reflect.TypeOf((*MockbooleanRepoInterface)(nil).UpdateBoolean), boolean)
}

// DeleteBooleanByID mocks base method
func (m *MockbooleanRepoInterface) DeleteBooleanByID(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBooleanByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBooleanByID indicates an expected call of DeleteBooleanByID
func (mr *MockbooleanRepoInterfaceMockRecorder) DeleteBooleanByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBooleanByID", reflect.TypeOf((*MockbooleanRepoInterface)(nil).DeleteBooleanByID), id)
}
